### ISSUE TITLE
[bug] Tendopay configuration 'Sandbox Mode' does not work and others

### ISSUE THREAD

**Issue by tangoslee** [TendoPayPlugins/tendopay-magento-1#2]
System > configuration > payment methods > Tendopay

1.  API always works in 'sandbox' mode,  

![screen shot 2019-01-15 at 4 22 55 pm](https://user-images.githubusercontent.com/42908571/51210862-dca4b200-18e1-11e9-9a6f-7a0a611951fe.png)

```php
// app/code/community/TendoPay/TendopayPayment/Helper/Data.php:208
    /**
     *
     * @return bool true if sandbox is enabled
     */
    private static function is_sandbox_enabled()
    {
        return true;
    }
```

2. Please remove 'Minimum Order', 'Maximum Order' 
![screen shot 2019-01-15 at 4 48 32 pm](https://user-images.githubusercontent.com/42908571/51213228-74a59a00-18e8-11e9-972c-8aeddbf313ae.png)

Currently, merchants cannot set those values. 

3.  The cart is empty when API communication fails.

In the issue1 (#1),  the cart items are cleared when the customer back to cart page after met API errors. The items in the cart should keep the items until the order succeed.   

4. Please provide a document; How to install the Tendopay plugin. 

5. Misspelling 

'Sendbox Mode'  [x]
'Sandbox Mode'  [O]

**Comment by tangoslee** [comment]
Thank you for modification. I've tested again. 

Done: 2. and 5

onGoing:
1. API always works in 'sandbox' mode,

it seems still has problems.  
* '$his' reference error in Data.php:444
*  isSandboxEnabled() always return 'active' whatever the admin chooses production or sandbox.

- details
```bash
[22-Jan-2019 19:21:33 UTC] PHP Fatal error:  Uncaught Error: Using $this when not in object context in /var/www/magento1/app/code/community/TendoPay/TendopayPayment/Helper/Data.php:444
Stack trace:
#0 /var/www/magento1/app/code/community/TendoPay/TendopayPayment/Helper/Data.php(205): TendoPay_TendopayPayment_Helper_Data::getConfigValues('active')
#1 /var/www/magento1/app/code/community/TendoPay/TendopayPayment/Helper/Data.php(175): TendoPay_TendopayPayment_Helper_Data::isSandboxEnabled()
#2 /var/www/magento1/app/code/community/TendoPay/TendopayPayment/controllers/StandardController.php(69): TendoPay_TendopayPayment_Helper_Data::get_authorization_endpoint_uri()
#3 /var/www/magento1/app/code/community/TendoPay/TendopayPayment/controllers/StandardController.php(97): TendoPay_TendopayPayment_StandardController->requestToken(Object(Mage_Sales_Model_Order))
#4 /var/www/magento1/app/code/core/Mage/Core/Controller/Varien/Action.php(418): TendoPay_TendopayPayment_StandardController->redirectAction()
#5 /var/www/magento1/app/code/core/Mage/Core/Controller/Varien/ in /var/www/magento1/app/code/community/TendoPay/TendopayPayment/Helper/Data.php on line 444
```

3. If the customer stops the payment process after checkout, the cart is clear and the stock of products is already deducted even though the payment has not completed. 
The cart and stock should be changed after the only when the payment completes successfully.

4. Installation Manual

Please review the above issues when you're available.

Thank you.

**Comment by piyushlathiya** [comment]
@tangoslee 

_1. API always works in 'sandbox' mode, it seems still has problems._
- Fixed
- https://github.com/TendoPayPlugins/tendopay-magento-1/commit/561c6c65ed52ca67499de53cdeb1ced87011a4a0

_2.  '$this' reference error in Data.php:444_
- Fixed
- https://github.com/TendoPayPlugins/tendopay-magento-1/commit/561c6c65ed52ca67499de53cdeb1ced87011a4a0

_3. An error encountered during generating hash_tocken_
- Refer Magento error: https://www.screencast.com/t/oD61EzdOee9j on http://magento1.tendopay.ph
- I thought it's issue from our side but when I tried it on Wordpress I got same error, https://www.screencast.com/t/DUcEqJODb on http://wp-piyush.cd-http.com/
- It occurs are occurred during /payments/api/v1/authTokenRequest request while generating hash_token for this API.
```
[message:protected] => Client error: `POST https://sandbox.tendopay.ph/payments/api/v1/authTokenRequest` resulted in a `422 Unprocessable Entity` response:
{"message":"The given data was invalid.","errors":{"tendopay_hash":["Incorrect or corrupted hash calculation."]}}
```
- It's look like something has been changed from TendoPay end, can you please confirm?

_4. If the customer stops the payment process after checkout, the cart is clear and the stock of products is already deducted even though the payment has not completed. The cart and stock should be changed after the only when the payment completes successfully._
- We've already implemented above logic but because above tendopay API error, it's not working.
- This is how Magento payment method works in general; When you choose a payment method and click on place order it will create one order in Magento, after customer complete payment they will be redirected to Magento with success/error response. Here based on response Magento will decide to complete order or cancel the order if there's any error then Magento will cancel that order (The cart and stock will be reset to the old one) and resetting existing items to cart.

----
**Other:**
Added guzzle using composer into lib directory and removed it from the module as to make it always up to date with the latest version.
- Commit: https://github.com/TendoPayPlugins/tendopay-magento-1/commit/d2330ad6d7abd94ea27cb02dbc6169eefc2da852

Thank you.
